name: 'Isabelle-action'
description: 'Isabelle image with prebuilt HOL'
inputs:
  args:
    description: 'Isabelle arguments'
    required: true
  heapCacheDir:
    description: 'path to save to/load from Isabelle session heap'
    required: false
  version:
    description: 'version of Isabelle to use'
    required: false
    default: Isabelle2021
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    HEAP_CACHE_DIR: ${{ inputs.heapCacheDir }}
  args:
    - ${{ inputs.version }}
    - ${{ inputs.args }}
